### ISSUE TITLE
Getting Intersection/Difference/Union to work

### ISSUE THREAD

**Issue by dogadogan** [xibyte/jsketcher#77]
Hello,

I tried to use the Intersection/Difference/Union features but I was not able to get them to work on my browser. It says: "requires 2 solids to be selected," but I wasn't able to figure out how to do so. I tried right clicking multiple solids and tried different key combinations but they didn't work. I would appreciate it if you could help! Thank you!

![screen shot 2018-11-27 at 14 33 58](https://user-images.githubusercontent.com/11411924/49106652-b6538600-f251-11e8-8e25-05d0c3c39136.png)

**Comment by mmiscool** [comment]
WHen this issue was created these commands were not implemented. 

These operations as of the latest master can be used with the 3d primitives available under the add menu in 3d. A wizard dialog will prompt for the selection of solids to use.  

![image](https://user-images.githubusercontent.com/6439772/77507878-aea0f300-6e3f-11ea-9952-9cec01a51c15.png)
